### PR TITLE
Update node action and remove cache action

### PR DESCRIPTION
**Pull request by samclarke**
Updates the actions to the latest versions, updates node and removes the cache action as the setup-node action now has built in cache support.

### CODE REVIEW

**Comment by live627** [comment]
This appears to change the cache dir from `node _modules` to `.npm`.

**Comment by samclarke** [comment]
Yeah I _think_ that's what it does. I did initially update cache-action but the docs recommended against caching `node_modules` and then I discovered setup-node has caching built in so figured might as well use that.

I think the reasons they recommend for not caching `node_modules` would be unlikely to occur but as far as I can tell the speed difference is minimal. Plus, these are run so infrequently that half the time the cache has expired anyway.

**Comment by live627** [comment]
it would skip `npm ci` if the cache was found.

**Review by live627 — APPROVED** [review]

**Comment by samclarke** [comment]
The difference includes skipping `npm ci`. Loading from the cache seems to be a little slow with GitHub actions which makes the difference fairly small (cache action takes ~6s, `npm ci` using built in cache option takes ~9s and `npm ci` without cache takes ~22s).

**Pull request merged**
