### PR TITLE
Ltr for code css

### PR DESCRIPTION
**Pull request by abetis**
Code segment should always be LTR, otherwise its incorrectly shown in RTL display mode.

### CODE REVIEW

**Comment by abetis** [comment]
Yes, the PR took many other  changes in my repository...

The change is only the addition of:
direction: ltr;
to the "code" css block.

**Comment by brunoais** [comment]
First, fix the branch. Then I can act. (same for all others)

**Comment by samclarke** [comment]
It might be easier to create a new PR with the change via the [Github web editor](https://github.com/samclarke/SCEditor/edit/master/src/themes/content/default.css) instead of trying to separate it out from all the other changes.

The actual CSS change looks good though 👍

**Comment by abetis** [comment]
Guys, that project is the first time I use git and GitHub, so it looks like the repository got messed up.
I don't mind to re-submit all the changes from a new and clean repository, but I need your help to setup the environment first.
This particular change is very small and can be applied without running the unit-tests, but all other changes are bigger and need to be tested.
It looks like the project's grunt scripts are not inline with the latest grunt requirements, so "grunt build" and "grunt test" fails.
I'm working on Ubuntu 16.04

Please help me help you.

Thanks.

**Comment by brunoais** [comment]
@samclarke ^

**Comment by samclarke** [comment]
Are you getting any error messages? I'm also using Ubuntu 16.04 and both grunt test and grunt build seem to be working for me. I've just cloned your fork and after running npm install grunt seems to be working with that too.

What version of node and grunt are you using?

**Comment by samclarke** [comment]
I've just realised, the webpack version has changed recently so if you're still using the old node_modules without updating then they will be out of sync. If you run `npm install` and then run grunt does it work?

**Comment by abetis** [comment]
@samclarke
I've tried to find a way to update everything, but it looks like everything is up to date.

`npm install` currently gives me:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3

the versions I have:
npm -v
3.5.2

nodejs -v
v4.2.6

grunt -V
grunt-cli v1.2.0
grunt v1.0.2

On a clean sceditor repository clone I get:
grunt build:
Running "clean:build" (clean) task
>> 1 path cleaned.

Running "copy:build" (copy) task
Created 1 directory, copied 2 files

Running "rollup:build" (rollup) task
The following options have been renamed — please update your config: interop -> output.interop
The following options have been renamed — please update your config: interop -> output.interop
Unknown option found: moduleId. Allowed keys: input, legacy, treeshake, acorn, context, moduleContext, plugins, onwarn, watch, cache, preferConst, experimentalDynamicImport, entry, external, extend, amd, banner, footer, intro, format, outro, sourcemap, sourcemapFile, name, globals, interop, legacy, freeze, indent, strict, noConflict, paths, exports, file, pureExternalModules
Unknown option found: moduleId. Allowed keys: input, legacy, treeshake, acorn, context, moduleContext, plugins, onwarn, watch, cache, preferConst, experimentalDynamicImport, entry, external, extend, amd, banner, footer, intro, format, outro, sourcemap, sourcemapFile, name, globals, interop, legacy, freeze, indent, strict, noConflict, paths, exports, file, pureExternalModules

Running "uglify:build" (uglify) task
>> 15 files created 684.91 kB → 287.85 kB

Running "less:build" (less) task
>> 6 stylesheets created.

Running "postcss:build" (postcss) task
>> 7 processed stylesheets created.

Done.



grunt test:
Running "eslint:source" (eslint) task

Running "eslint:tests" (eslint) task

Running "eslint:translations" (eslint) task

Running "dev-server" task
Warning: Unexpected token { Use --force to continue.

Aborted due to warnings.


Please advise what to do.
Thanks.

**Comment by abetis** [comment]
`npm outdated` doesn't show that something should be updated.

npm list | grep webpack
├─┬ webpack@4.4.1
│ ├─┬ uglifyjs-webpack-plugin@1.2.4
│ └─┬ webpack-sources@1.1.0
└─┬ webpack-dev-server@3.1.1
  ├─┬ webpack-dev-middleware@3.0.1
  ├─┬ webpack-log@1.1.2

**Comment by samclarke** [comment]
I've just checked and it looks like webpack 4 doesn't support node v4 which I'm guessing is the issue.

Not sure what to do about this. We could downgrade webpack to the previous version as it would be nice to have Ubuntu 16.04 work out of the box. The downside is that 16.04 is supported until 2021 while offical node v4 support ends then end of this month. It would be a long time to be stuck on with an old node version and other packages will likely start breaking soon so not sure if that's a great idea.

If you can, [updating node to a newer version](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) should fix it or using something like n ot nvm to manage node versions.

**Comment by abetis** [comment]
Thanks for the fast response.
That's one of the downsides of the community maintained code, no one takes the dependencies seriously...

I've manually installed 9.x version and it looks like working with some warnings and deprecated notifications:
grunt build still gives the same warnings:
Running "rollup:build" (rollup) task
The following options have been renamed — please update your config: interop -> output.interop
The following options have been renamed — please update your config: interop -> output.interop
Unknown option found: moduleId. Allowed keys: input, legacy, treeshake, acorn, context, moduleContext, plugins, onwarn, watch, cache, preferConst, experimentalDynamicImport, entry, external, extend, amd, banner, footer, intro, format, outro, sourcemap, sourcemapFile, name, globals, interop, legacy, freeze, indent, strict, noConflict, paths, exports, file, pureExternalModules
Unknown option found: moduleId. Allowed keys: input, legacy, treeshake, acorn, context, moduleContext, plugins, onwarn, watch, cache, preferConst, experimentalDynamicImport, entry, external, extend, amd, banner, footer, intro, format, outro, sourcemap, sourcemapFile, name, globals, interop, legacy, freeze, indent, strict, noConflict, paths, exports, file, pureExternalModules

grunt test complains, but works:
Running "dev-server" task
(node:1780) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢wdm｣: Hash: 332556f387848f0b6411

I will start with a new fresh repo and push the changes again

**Comment by abetis** [comment]
Replaced by #670

**Pull request closed without merging**
